[package]
name = "omnisette"
version = "0.1.0"
edition = "2021"

[features]
remote-anisette = []
default = ["remote-anisette"]

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[target.'cfg(not(target_env = "macos"))'.dependencies]
android-loader = { git = "https://github.com/Dadoum/android-loader" }
base64 = "0.21.0"
chrono = "0.4.21"
libc = "0.2.139"
machineid-rs = "1.2.2"
plist = "1.4.0"
rand = "0.8.4"

[target.'cfg(target_env = "macos")'.dependencies]
dlopen2 = "0.4.1"
objc = "0.2.7"
objc-foundation = "0.1.1"
