[package]
name = "omnisette"
version = "0.1.0"
edition = "2021"

[features]
remote-anisette = []
default = ["remote-anisette"]

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }

[target.'cfg(not(target_env = "macos"))'.dependencies]
android-loader = { git = "https://github.com/Dadoum/android-loader" }

[target.'cfg(target_env = "macos")'.dependencies]
dlopen2 = "0.4.1"
objc = "0.2.7"
objc-foundation = "0.1.1"
